[tool.poetry]
name = "any_case"
version = "0.1.0"
description = ""
authors = ["asduj <asduj@ya.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
